name: Hassfest

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions: {}

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master
